#ifndef MAIN_CLOUD_MANAGER_H_
#define MAIN_CLOUD_MANAGER_H_

#include "esp_event.h"
#include "report_manager.h"

#define CLOUD_ID_MAX_LEN 128
#define CLOUD_PSK_MAX_LEN 128
#define CLOUD_LOG_MAX_LEN 52

/* events generated by cloud manager */
typedef enum
{
	CLOUD_EVENT_CONNECTED,
	CLOUD_EVENT_DISCONNECTED,
	CLOUD_EVENT_LED,
	CLOUD_EVENT_OPEN,
	CLOUD_EVENT_MAX
} cloud_event_t;

/* wiegand event data */
typedef struct
{
	uint64_t code;
	uint8_t code_len;
} cloud_wiegand_data_t;

ESP_EVENT_DECLARE_BASE(CLOUD_EVENT);

void cloud_init(esp_event_loop_handle_t event_loop);
void cloud_join(char *id, char *psk);
void cloud_leave(void);
void cloud_log(const char *tag, const char *format, ...);
void cloud_report(report_data_t *report);

#endif /* MAIN_CLOUD_MANAGER_H_ */
